spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:test}
        secret-key: ${AWS_SECRET_ACCESS_KEY:test}
      region:
        static: ${AWS_DEFAULT_REGION:us-east-1}
      s3:
        endpoint: ${AWS_S3_ENDPOINT:http://localhost:4566}
        path-style-access-enabled: true
