spring:
  kafka:
    streams:
      bootstrap-servers: ${APP_KAFKA_URL:localhost:9095}
      application-id: embedded-streaming-apache-kafka
    consumer:
      group-id: ${APP_KAFKA_GROUP_ID:main-group}
