spring:
  kafka:
    topic:
      name: ${APP_KAFKA_TOPIC_NAME:cdc.tutorial_db.example_table}
    consumer:
      group-id: ${APP_KAFKA_GROUP_ID:cdc.tutorial_db.main-group}
    bootstrap-servers: ${APP_KAFKA_URL:localhost:9092}
